#!/bin/bash

if [[ -z "${NTHREADS}" ]]; then NTHREADS=1; fi

QPS=${QPS:-1000}
REQUESTS=${REQUESTS:-3000}
WARMUPREQS=${WARMUPREQS:-14000}

if [ ! -z RANDSEED ] ; then
    export TBENCH_RANDSEED=$RANDSEED
fi

TBENCH_QPS=${QPS} TBENCH_MAXREQS=${REQUESTS} TBENCH_WARMUPREQS=${WARMUPREQS} \
    TBENCH_MINSLEEPNS=10000 ./mttest_integrated -j${NTHREADS} \
    mycsba masstree

